src/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('google/', include('googler.urls')),
]

src/googler/urls.py
from django.urls import path

from googler import views

app_name = 'googler'

urlpatterns = [
    path('login/', views.google_login_view, name='login'),
    path('callback/', views.google_login_callback_view, name='callback'),
]

src/googler/models.py
from django.db import models

# Create your models here.

src/googler/views.py
from django.conf import settings
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import redirect, render

from . import oauth, services

LOGIN_REDIRECT_URL = settings.LOGIN_REDIRECT_URL
# 

def google_login_view(request):
    if request.method == "POST":
        # csrf_token security
        google_oauth2_url = oauth.generate_auth_url()
        return redirect(google_oauth2_url)
    return render(request, "googler/login.html", {})


def google_login_callback_view(request):
    # print(request.GET)
    state = request.GET.get('state')
    code = request.GET.get('code')
    try:
        token_json = oauth.verify_google_oauth_callback(state, code)
    except Exception as e:
        return HttpResponse(f"{e}", status=400)
    google_user_info = oauth.verify_token_json(token_json)
    user = services.get_or_create_google_user(google_user_info)
    # save_google_auth_tokens(user, google_user_info, token_json)
    login(request, user)
    return redirect(LOGIN_REDIRECT_URL)

src/googler/templates/googler/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>
    <div class="relative flex items-center my-4 mt-10">
        <div class="flex-grow border-t border-gray-300"></div>
        <span class="px-3 text-gray-500 text-sm">OR</span>
        <div class="flex-grow border-t border-gray-300"></div>
    </div>
    
    <div class="w-full md:w-80 my-8 m-auto space-y-3 font-semibold">
        <form action="{% url 'googler:login' %}" method="POST">
            {% csrf_token %}
    
        <button class="relative flex items-center p-4 rounded-full border !no-underline hover:!text-inherit hover:!bg-gray-100 w-full">
            <svg class="w-6 h-6 absolute left-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
                <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path>
                <path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path>
                <path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path>
                <path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
            </svg>
            <span class="text-center w-full">Sign in with Google</span>
        </button>
    
        <a class="relative flex items-center p-4 rounded-full border !no-underline hover:!text-inherit hover:!bg-gray-100 w-full" href="">
            <svg class="w-6 h-6 absolute left-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M12 2C6.48 2 2 6.48 2 12c0 4.42 2.87 8.18 6.84 9.5.5.09.66-.22.66-.48 0-.24-.01-1.04-.01-1.9-2.78.58-3.37-1.18-3.37-1.18-.45-1.15-1.1-1.46-1.1-1.46-.9-.62.07-.6.07-.6 1 .07 1.52 1.03 1.52 1.03.9 1.51 2.36 1.07 2.94.82.09-.66.35-1.07.63-1.31-2.22-.25-4.56-1.11-4.56-4.95 0-1.09.39-1.99 1.03-2.69-.1-.26-.45-1.29.1-2.69 0 0 .84-.27 2.75 1.02a9.56 9.56 0 0 1 5 0c1.91-1.29 2.75-1.02 2.75-1.02.55 1.4.2 2.43.1 2.69.64.7 1.03 1.6 1.03 2.69 0 3.85-2.34 4.7-4.57 4.95.36.31.68.91.68 1.84 0 1.33-.01 2.41-.01 2.74 0 .26.16.58.67.48A10.012 10.012 0 0 0 22 12c0-5.52-4.48-10-10-10z"/>
            </svg>
            <span class="text-center w-full">Sign in with GitHub</span>
        </a>
    
        <a class="relative flex items-center p-4 rounded-full border !no-underline hover:!text-inherit hover:!bg-gray-100 w-full" href="">
            <svg class="w-6 h-6 absolute left-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
                <path d="M 5.9199219 6 L 20.582031 27.375 L 6.2304688 44 L 9.4101562 44 L 21.986328 29.421875 L 31.986328 44 L 44 44 L 28.681641 21.669922 L 42.199219 6 L 39.029297 6 L 27.275391 19.617188 L 17.933594 6 L 5.9199219 6 z M 9.7167969 8 L 16.880859 8 L 40.203125 42 L 33.039062 42 L 9.7167969 8 z"></path>
            </svg>
            <span class="text-center w-full">Sign in with X</span>
        </a>
    
        <a class="relative flex items-center p-4 rounded-full border !no-underline hover:!text-inherit hover:!bg-gray-100 w-full" href="">
            <svg class="w-6 h-6 text-blue-600 absolute left-4" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                <path d="M22 12.07C22 6.48 17.52 2 12 2S2 6.48 2 12.07c0 5.02 3.66 9.18 8.44 9.93v-7.03h-2.5v-2.9h2.5V9.41c0-2.46 1.49-3.82 3.74-3.82 1.08 0 2.2.19 2.2.19v2.42h-1.24c-1.22 0-1.6.76-1.6 1.54v1.84h2.72l-.44 2.9h-2.28v7.03c4.78-.75 8.44-4.91 8.44-9.93z"/>
            </svg>
            <span class="text-center w-full">Sign in with Facebook</span>
        </a>
    </form>
    </div>
</body>
</html>